import asyncio
import json
import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from app.agents.card_schema import JSONMemoryCard
from app.llm.llm_client import llm_client


class DeliverableAgent:
    """The 1-Click Deliverable Forge of Jarvis:
    Transforms raw memory cards and browsing evidence into finished, publication-grade documents:
    - Academic Literature Review (with methodology and citations)
    - High-Yield Exam / Concept Cheatsheet
    - Production Software Architecture Specification
    - Executive Intelligence Briefing
    """

    def __init__(self, vault_root: str = "memory_vault"):
        self.project_root = Path(__file__).resolve().parents[3]
        self.vault_root = self.project_root / vault_root
        self.deliverables_dir = self.vault_root / "deliverables"
        self.deliverables_dir.mkdir(parents=True, exist_ok=True)

    async def generate_deliverable(
        self,
        deliverable_type: str,  # 'research_paper' | 'cheatsheet' | 'architecture_spec' | 'executive_summary'
        topic: str,
        cards: List[JSONMemoryCard],
        user_instructions: str = ""
    ) -> Dict:
        now = datetime.utcnow()
        timestamp_str = now.strftime("%Y-%m-%d %H:%M UTC")

        # Compile context from cards
        evidence_text = ""
        entities = set()
        for i, c in enumerate(cards[:15], 1):
            evidence_text += f"\n[Evidence {i}] Topic: {c.topic} | Domain: {c.domain} | Source: {c.app_source}\n"
            evidence_text += f"Summary: {c.summary}\n"
            if c.key_pointers:
                evidence_text += "Pointers:\n" + "\n".join(f"  - {p}" for p in c.key_pointers) + "\n"
            entities.update(c.entities)

        prompts = {
            "research_paper": (
                f"You are JARVIS operating as a Principal Research Scientist. "
                f"Synthesize a formal academic literature review and technical paper on '{topic}'. "
                f"Structure: Abstract, I. Introduction & Background, II. Core Methodology & Concepts, "
                f"III. Key Findings & Empirical Observations, IV. Practical Applications & Gaps, V. Conclusion. "
                f"Use academic rigor, formal scientific phrasing, and numbered citations [1], [2]. "
                f"Synthesize the following captured evidence into cohesive prose (do not just copy bullet points):\n{evidence_text}"
            ),
            "cheatsheet": (
                f"You are JARVIS operating as a Senior Master Tutor. "
                f"Synthesize a high-yield, comprehensive exam and revision cheatsheet on '{topic}'. "
                f"Structure: Executive Core Definition, Essential Formulas & Principles, Key Conceptual Breakdown, "
                f"High-Yield Gotchas & Common Pitfalls, 10-Second Recall Checklist. "
                f"Make it punchy, deeply organized, and visually clear using Markdown tables and code snippets where appropriate.\n{evidence_text}"
            ),
            "architecture_spec": (
                f"You are JARVIS operating as a Chief Systems Architect. "
                f"Synthesize a production-grade software and system architecture specification for '{topic}'. "
                f"Structure: 1. System Overview & Objectives, 2. High-Level Architecture & Data Flow, "
                f"3. Component Breakdown & Protocols, 4. Performance, Latency & Storage Invariants, "
                f"5. Security Guardrails & Resiliency. Include ASCII or Markdown architecture diagrams.\n{evidence_text}"
            ),
            "executive_summary": (
                f"You are JARVIS operating as an Executive Intelligence Director. "
                f"Synthesize a high-impact strategic intelligence briefing on '{topic}'. "
                f"Structure: 1. Strategic Bottom Line, 2. Key Intelligence Pointers, "
                f"3. Technological & Competitive Implications, 4. Recommended Next Actions.\n{evidence_text}"
            )
        }

        system_prompt = prompts.get(deliverable_type, prompts["research_paper"])
        if user_instructions:
            system_prompt += f"\nAdditional User Directives: {user_instructions}"

        messages = [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": f"Synthesize deliverable for topic: {topic}. Timestamp: {timestamp_str}."}
        ]

        document_content = ""
        try:
            async for token in llm_client.stream(messages, []):
                document_content += token
        except Exception as e:
            document_content = f"# Autonomous Deliverable: {topic}\n*Generated by Jarvis Deliverable Forge*\n\nUnable to generate full document: {e}"

        # Save to disk
        slug = "".join(c if c.isalnum() else "_" for c in topic).strip("_").lower()
        filename = f"{deliverable_type}_{slug}_{now.strftime('%Y%m%d_%H%M%S')}.md"
        file_path = self.deliverables_dir / filename
        file_path.write_text(document_content, encoding="utf-8")

        result = {
            "id": f"deliv_{now.strftime('%Y%m%d_%H%M%S')}",
            "filename": filename,
            "title": f"{deliverable_type.replace('_', ' ').title()}: {topic}",
            "deliverable_type": deliverable_type,
            "topic": topic,
            "created_at": timestamp_str,
            "word_count": len(document_content.split()),
            "content": document_content,
            "path": f"memory_vault/deliverables/{filename}"
        }

        print(f"[DeliverableAgent] Forged new deliverable: {filename} ({result['word_count']} words)")
        return result

    def list_deliverables(self) -> List[Dict]:
        """Lists all forged deliverables from memory_vault/deliverables/."""
        results = []
        if not self.deliverables_dir.exists():
            return []

        for md_file in sorted(self.deliverables_dir.glob("*.md"), key=lambda p: p.stat().st_mtime, reverse=True):
            try:
                content = md_file.read_text(encoding="utf-8")
                lines = content.split("\n")
                title = lines[0].replace("#", "").strip() if lines else md_file.stem
                results.append({
                    "filename": md_file.name,
                    "title": title,
                    "created_at": datetime.fromtimestamp(md_file.stat().st_mtime).strftime("%Y-%m-%d %H:%M"),
                    "word_count": len(content.split()),
                    "preview": "\n".join(lines[1:5]).strip(),
                    "path": f"memory_vault/deliverables/{md_file.name}"
                })
            except Exception:
                pass
        return results


deliverable_agent = DeliverableAgent()
